"""OpenAPI documentation quality contract (SWAGGER-002).

Guards the public-facing Swagger/OpenAPI documentation against regression:
every operation must be genuinely documented, the ApiKeyAuth/Idempotency-Key
UX must stay intact, error responses must reflect this application's real
ErrorEnvelope contract (never FastAPI's default validation shape), and no
internal ticket/ADR marker may leak into public descriptions. Semantic
assertions only -- no snapshot of the whole schema.
"""

from __future__ import annotations

import json
import re
from typing import Any

import httpx
import pytest

from sofias_memory.config import Settings
from tests.unit._app_factory import create_app

EXPECTED_API_KEY = "sf-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
DATABASE_URL = "postgresql+asyncpg://sofias_memory:fake@postgres:5432/sofias_memory"
NEO4J_PASSWORD = "fake-neo4j-password"
LLM_API_KEY = "sk-fake-test-key"

INTERNAL_MARKER_PATTERN = re.compile(r"SM-\d|ADR-\d|\bB5\b|\bB4\b|\bB3\b")

# Idempotency-Key is accepted only by these operations (verified against the
# route code, not docs/api.md) -- SWAGGER-002 SS10.
IDEMPOTENCY_KEY_OPERATIONS = {
    ("post", "/api/v1/remember"),
    ("post", "/api/v1/remember/file"),
    ("post", "/api/v1/remember/url"),
    ("post", "/api/v1/cognify"),
    ("post", "/api/v1/improve"),
    ("post", "/api/v1/forget"),
}

HTTP_METHODS = ("get", "post", "put", "patch", "delete")


def make_settings(**overrides: object) -> Settings:
    values: dict[str, object] = {
        "api_key": EXPECTED_API_KEY,
        "database_url": DATABASE_URL,
        "neo4j_password": NEO4J_PASSWORD,
        "llm_api_key": LLM_API_KEY,
        "app_name": "Sofias Memory Test",
        "app_version": "9.8.7",
        "app_env": "development",
    }
    values.update(overrides)
    return Settings(_env_file=None, **values)  # type: ignore[call-arg]


def openapi_schema() -> dict[str, Any]:
    app = create_app(make_settings())
    return app.openapi()


def _operations(schema: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    operations: list[tuple[str, str, dict[str, Any]]] = []
    for path, path_item in schema["paths"].items():
        for method, operation in path_item.items():
            if method in HTTP_METHODS:
                operations.append((method, path, operation))
    return operations


def test_info_description_is_non_empty() -> None:
    schema = openapi_schema()
    assert len(schema["info"].get("description", "")) > 100


def test_every_used_tag_has_metadata() -> None:
    schema = openapi_schema()
    documented_tags = {tag["name"] for tag in schema.get("tags", [])}
    used_tags: set[str] = set()
    for _method, _path, operation in _operations(schema):
        used_tags.update(operation.get("tags", []))
    assert used_tags, "expected at least one tagged operation"
    assert used_tags <= documented_tags


def test_every_tag_has_a_description() -> None:
    schema = openapi_schema()
    for tag in schema.get("tags", []):
        assert tag.get("description"), f"tag {tag['name']!r} has no description"


def test_every_operation_has_summary_and_description() -> None:
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        assert operation.get("summary"), f"{method.upper()} {path} has no summary"
        assert operation.get("description"), f"{method.upper()} {path} has no description"


def test_every_operation_summary_is_not_generic_autogenerated_text() -> None:
    # A generic FastAPI-autogenerated summary looks like "Remember Text" (the
    # function name title-cased) with no punctuation/context -- catching an
    # exact one-word match would be too strict, so this only guards against
    # an empty or whitespace-only summary slipping through as "documented".
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        summary = operation.get("summary", "")
        assert summary.strip(), f"{method.upper()} {path} has a blank summary"


def test_all_v1_operations_require_api_key_security() -> None:
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        if path.startswith("/api/v1/"):
            assert operation.get("security") == [{"ApiKeyAuth": []}], (
                f"{method.upper()} {path} is missing ApiKeyAuth security"
            )


def test_health_operations_do_not_require_api_key() -> None:
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        if path.startswith("/health/"):
            assert operation.get("security") in (None, []), (
                f"{method.upper()} {path} must not require ApiKeyAuth"
            )


def test_api_key_security_scheme_has_a_useful_description() -> None:
    schema = openapi_schema()
    scheme = schema["components"]["securitySchemes"]["ApiKeyAuth"]
    assert scheme["type"] == "apiKey"
    assert scheme["in"] == "header"
    assert scheme["name"] == "X-API-Key"
    assert len(scheme.get("description", "")) > 20


def test_invalid_api_key_response_is_403_error_envelope() -> None:
    schema = openapi_schema()
    _method, _path, operation = next(
        (m, p, o) for m, p, o in _operations(schema) if p == "/api/v1/info"
    )
    response = operation["responses"]["403"]
    schema_ref = response["content"]["application/json"]["schema"]["$ref"]
    assert schema_ref == "#/components/schemas/ErrorEnvelope"


def test_missing_api_key_response_is_401_error_envelope() -> None:
    schema = openapi_schema()
    _method, _path, operation = next(
        (m, p, o) for m, p, o in _operations(schema) if p == "/api/v1/info"
    )
    response = operation["responses"]["401"]
    schema_ref = response["content"]["application/json"]["schema"]["$ref"]
    assert schema_ref == "#/components/schemas/ErrorEnvelope"


def test_validation_error_response_uses_error_envelope_not_http_validation_error() -> None:
    schema = openapi_schema()
    _method, _path, operation = next(
        (m, p, o) for m, p, o in _operations(schema) if p == "/api/v1/remember"
    )
    response = operation["responses"]["422"]
    schema_ref = response["content"]["application/json"]["schema"]["$ref"]
    assert schema_ref == "#/components/schemas/ErrorEnvelope"


def test_http_validation_error_schema_is_not_advertised() -> None:
    schema = openapi_schema()
    component_schemas = schema["components"]["schemas"]
    assert "HTTPValidationError" not in component_schemas
    assert "ValidationError" not in component_schemas


def test_idempotency_key_has_meaningful_description_where_accepted() -> None:
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        if (method, path) not in IDEMPOTENCY_KEY_OPERATIONS:
            continue
        header_param = next(
            (
                p
                for p in operation.get("parameters", [])
                if p.get("name") == "Idempotency-Key" and p.get("in") == "header"
            ),
            None,
        )
        assert header_param is not None, f"{method.upper()} {path} is missing Idempotency-Key"
        assert header_param.get("required") is not True
        description = header_param["schema"].get("description", header_param.get("description", ""))
        assert len(description) > 50


def test_idempotency_key_absent_from_operations_that_do_not_accept_it() -> None:
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        if (method, path) in IDEMPOTENCY_KEY_OPERATIONS or not path.startswith("/api/v1/"):
            continue
        header_names = {p.get("name") for p in operation.get("parameters", [])}
        assert "Idempotency-Key" not in header_names, (
            f"{method.upper()} {path} unexpectedly documents Idempotency-Key"
        )


def test_no_internal_ticket_or_adr_markers_leak_into_schema() -> None:
    schema = openapi_schema()
    serialized = json.dumps(schema)
    matches = INTERNAL_MARKER_PATTERN.findall(serialized)
    assert matches == []


def _make_client(app: Any) -> httpx.AsyncClient:
    transport = httpx.ASGITransport(app=app, raise_app_exceptions=False)
    return httpx.AsyncClient(transport=transport, base_url="http://testserver")


@pytest.mark.asyncio
async def test_docs_openapi_redoc_environment_gating_still_intact() -> None:
    # SWAGGER-001 regression guard, kept alive here since SWAGGER-002 touches
    # the same create_app()/FastAPI construction.
    async with _make_client(create_app(make_settings(app_env="development"))) as client:
        assert (await client.get("/docs")).status_code == 200
        assert (await client.get("/openapi.json")).status_code == 200
        assert (await client.get("/redoc")).status_code == 404

    async with _make_client(create_app(make_settings(app_env="production"))) as client:
        assert (await client.get("/docs")).status_code == 404
        assert (await client.get("/openapi.json")).status_code == 404
        assert (await client.get("/redoc")).status_code == 404


# --- Route-specific error documentation (SWAGGER-002 staging fix) -----------
#
# Every status/code pair below was confirmed against the service code that
# actually raises it before being asserted here -- see the route-specific
# error constants in sofias_memory/api/openapi_responses.py and their
# corresponding services (pipeline_submission.py, dataset_delete.py,
# dataset_delete_barrier.py, run_control.py) for the source of truth.


def _response_for(schema: dict[str, Any], method: str, path: str, status: str) -> dict[str, Any]:
    operation = schema["paths"][path][method]
    response: dict[str, Any] = operation["responses"][status]
    return response


def _assert_error_envelope(response: dict[str, Any]) -> None:
    schema_ref = response["content"]["application/json"]["schema"]["$ref"]
    assert schema_ref == "#/components/schemas/ErrorEnvelope"


def test_dataset_not_found_404_documented_on_get_dataset() -> None:
    schema = openapi_schema()
    response = _response_for(schema, "get", "/api/v1/datasets/{dataset_id}", "404")
    _assert_error_envelope(response)
    assert "INVALID_REQUEST" in response["description"]


def test_idempotency_conflict_409_documented_on_remember() -> None:
    schema = openapi_schema()
    response = _response_for(schema, "post", "/api/v1/remember", "409")
    _assert_error_envelope(response)
    assert "IDEMPOTENCY_CONFLICT" in response["description"]


def test_reserved_idempotency_namespace_400_documented_on_cognify() -> None:
    schema = openapi_schema()
    response = _response_for(schema, "post", "/api/v1/cognify", "400")
    _assert_error_envelope(response)
    assert "RESERVED_IDEMPOTENCY_KEY_NAMESPACE" in response["description"]


def test_worker_disabled_503_documented_on_improve() -> None:
    schema = openapi_schema()
    response = _response_for(schema, "post", "/api/v1/improve", "503")
    _assert_error_envelope(response)
    assert "WORKER_DISABLED" in response["description"]


def test_worker_disabled_503_documented_on_dataset_delete() -> None:
    # Administrative Dataset DELETE submits through its own service, not the
    # generic PipelineSubmissionService, but still checks worker availability
    # for a brand-new deletion run (services/dataset_delete.py).
    schema = openapi_schema()
    response = _response_for(schema, "delete", "/api/v1/datasets/{dataset_id}", "503")
    _assert_error_envelope(response)
    assert "WORKER_DISABLED" in response["description"]


def test_main_dataset_delete_forbidden_409_documented() -> None:
    schema = openapi_schema()
    response = _response_for(schema, "delete", "/api/v1/datasets/{dataset_id}", "409")
    _assert_error_envelope(response)
    assert "MAIN_DATASET_DELETE_FORBIDDEN" in response["description"]


def test_run_not_retryable_409_documented_on_retry() -> None:
    schema = openapi_schema()
    response = _response_for(schema, "post", "/api/v1/runs/{run_id}/retry", "409")
    _assert_error_envelope(response)
    assert "RUN_NOT_RETRYABLE" in response["description"]


def test_run_not_found_404_documented_on_get_run_cancel_and_retry() -> None:
    schema = openapi_schema()
    for method, path in [
        ("get", "/api/v1/runs/{run_id}"),
        ("post", "/api/v1/runs/{run_id}/cancel"),
        ("post", "/api/v1/runs/{run_id}/retry"),
    ]:
        response = _response_for(schema, method, path, "404")
        _assert_error_envelope(response)


def test_cancel_run_has_no_artificial_503_or_409() -> None:
    # Cancel is a pure status flip -- it never submits new work, so it can
    # never produce WORKER_DISABLED, IDEMPOTENCY_CONFLICT, or a dataset
    # administrative-delete conflict. Only 404 (run not found) is real.
    schema = openapi_schema()
    responses = schema["paths"]["/api/v1/runs/{run_id}/cancel"]["post"]["responses"]
    assert "503" not in responses
    assert "409" not in responses


def test_read_only_list_operations_have_no_artificial_503() -> None:
    # GET /runs and GET /datasets never submit work and never touch the
    # worker or Neo4j -- 503 must not be added just for visual consistency.
    schema = openapi_schema()
    for path in ["/api/v1/runs", "/api/v1/datasets"]:
        responses = schema["paths"][path]["get"]["responses"]
        assert "503" not in responses


def test_graph_dependency_unavailable_503_documented() -> None:
    schema = openapi_schema()
    for path in ["/api/v1/graph/schema", "/api/v1/graph/subgraph", "/api/v1/graph/path"]:
        response = _response_for(schema, "get", path, "503")
        _assert_error_envelope(response)
        assert "DEPENDENCY_UNAVAILABLE" in response["description"]


def test_provenance_not_found_404_documented() -> None:
    schema = openapi_schema()
    for path in [
        "/api/v1/provenance/source/{source_id}",
        "/api/v1/provenance/relation/{relation_id}",
        "/api/v1/provenance/query/{query_id}",
    ]:
        response = _response_for(schema, "get", path, "404")
        _assert_error_envelope(response)


def test_all_route_specific_error_responses_use_error_envelope() -> None:
    schema = openapi_schema()
    for method, path, operation in _operations(schema):
        for status, response in operation["responses"].items():
            if status in ("200", "201", "202"):
                continue
            assert "content" in response, f"{method.upper()} {path} {status} has no content"
            _assert_error_envelope(response)


# --- Documentation-only Swagger schema (manual UX finding) ------------------
#
# /docs renders from a separate, human-facing schema (/openapi-docs.json)
# that strips the Idempotency-Key header parameter -- the canonical
# /openapi.json is untouched and remains the source of truth.


def _idempotency_key_params(schema: dict[str, Any]) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for path, path_item in schema["paths"].items():
        for method, operation in path_item.items():
            if method not in HTTP_METHODS:
                continue
            for parameter in operation.get("parameters", []):
                if (
                    parameter.get("in") == "header"
                    and str(parameter.get("name", "")).lower() == "idempotency-key"
                ):
                    found.append((method, path))
    return found


def documentation_schema() -> dict[str, Any]:
    from sofias_memory.app import _documentation_schema

    return _documentation_schema(openapi_schema())


def test_canonical_schema_has_exactly_six_idempotency_key_parameters() -> None:
    canonical = openapi_schema()
    matches = _idempotency_key_params(canonical)
    assert len(matches) == 6
    assert set(matches) == IDEMPOTENCY_KEY_OPERATIONS


def test_documentation_schema_has_zero_idempotency_key_parameters() -> None:
    doc_schema = documentation_schema()
    assert _idempotency_key_params(doc_schema) == []


def test_documentation_schema_does_not_mutate_canonical_schema() -> None:
    canonical_before = openapi_schema()
    idem_before = len(_idempotency_key_params(canonical_before))
    documentation_schema()
    canonical_after = openapi_schema()
    assert len(_idempotency_key_params(canonical_after)) == idem_before == 6


def test_canonical_and_documentation_schemas_share_identical_paths_and_methods() -> None:
    canonical = openapi_schema()
    doc_schema = documentation_schema()
    assert set(canonical["paths"].keys()) == set(doc_schema["paths"].keys())
    for path, path_item in canonical["paths"].items():
        canonical_methods = {m for m in path_item if m in HTTP_METHODS}
        doc_methods = {m for m in doc_schema["paths"][path] if m in HTTP_METHODS}
        assert canonical_methods == doc_methods, path


def test_canonical_and_documentation_schemas_share_identical_bodies_and_responses() -> None:
    canonical = openapi_schema()
    doc_schema = documentation_schema()
    for method, path, operation in _operations(canonical):
        doc_operation = doc_schema["paths"][path][method]
        assert operation.get("requestBody") == doc_operation.get("requestBody"), path
        assert operation.get("responses") == doc_operation.get("responses"), path
        assert operation.get("security") == doc_operation.get("security"), path


def test_only_parameter_difference_between_schemas_is_idempotency_key() -> None:
    canonical = openapi_schema()
    doc_schema = documentation_schema()
    for method, path, operation in _operations(canonical):
        canonical_params = operation.get("parameters", [])
        doc_params = doc_schema["paths"][path][method].get("parameters", [])
        expected_doc_params = [
            p
            for p in canonical_params
            if not (p.get("in") == "header" and str(p.get("name", "")).lower() == "idempotency-key")
        ]
        assert doc_params == expected_doc_params, path


def test_openapi_docs_json_and_docs_are_not_operations_in_either_schema() -> None:
    for schema in (openapi_schema(), documentation_schema()):
        assert "/openapi-docs.json" not in schema["paths"]
        assert "/docs" not in schema["paths"]


def test_security_schemes_identical_across_schemas() -> None:
    canonical = openapi_schema()
    doc_schema = documentation_schema()
    assert canonical["components"]["securitySchemes"] == doc_schema["components"]["securitySchemes"]


@pytest.mark.asyncio
async def test_docs_renders_and_openapi_docs_json_is_reachable_in_development() -> None:
    app = create_app(make_settings(app_env="development"))
    async with _make_client(app) as client:
        docs_response = await client.get("/docs")
        assert docs_response.status_code == 200
        assert "swagger-ui" in docs_response.text.lower()
        assert "/openapi-docs.json" in docs_response.text

        doc_json_response = await client.get("/openapi-docs.json")
        assert doc_json_response.status_code == 200
        assert _idempotency_key_params(doc_json_response.json()) == []

        canonical_response = await client.get("/openapi.json")
        assert canonical_response.status_code == 200
        assert len(_idempotency_key_params(canonical_response.json())) == 6


@pytest.mark.asyncio
async def test_openapi_docs_json_gated_same_as_docs_outside_development() -> None:
    for env in ("production", "test", "something-unexpected"):
        app = create_app(make_settings(app_env=env))
        async with _make_client(app) as client:
            assert (await client.get("/docs")).status_code == 404
            assert (await client.get("/openapi.json")).status_code == 404
            assert (await client.get("/openapi-docs.json")).status_code == 404
            assert (await client.get("/redoc")).status_code == 404
